# Generated by Django 3.2.9 on 2022-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_heading', models.CharField(max_length=255)),
                ('blog_heading', models.CharField(blank=True, max_length=255)),
                ('blog_content', models.TextField()),
                ('blog_image', models.CharField(max_length=255)),
                ('publish_date', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content_source', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
